"""Debug logging utilities for saving LLM responses and prompts."""

import logging
import pandas as pd
from pathlib import Path

logger = logging.getLogger(__name__)


def save_llm_response(stock_symbol: str, section_name: str, response_content: str):
    """Save LLM responses to files for debugging timeout issues."""
    try:
        response_dir = Path(__file__).parent.parent.parent / "llm_responses"
        response_dir.mkdir(exist_ok=True)
        
        # Create a file with stock name and section
        timestamp = Path(f"response_{Path(stock_symbol).name}_{section_name}_{pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')}.txt")
        filepath = response_dir / timestamp
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"Stock: {stock_symbol}\n")
            f.write(f"Section: {section_name}\n")
            f.write(f"Timestamp: {pd.Timestamp.now()}\n")
            f.write(f"Response Length: {len(response_content)} chars\n")
            f.write("="*80 + "\n\n")
            f.write(response_content)
        
        logger.info(f"Saved LLM response to {filepath}")
    except Exception as e:
        logger.warning(f"Could not save LLM response: {e}")


def save_prompt_to_files(stock_symbol: str, section_name: str, prompt_content: str):
    """Save prompt content as both markdown and HTML files for inspection."""
    try:
        prompts_dir = Path(__file__).parent.parent.parent / "debug_prompts"
        prompts_dir.mkdir(exist_ok=True)
        
        timestamp = pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')
        
        # Save as markdown
        md_filename = f"prompt_{stock_symbol}_{section_name}_{timestamp}.md"
        md_filepath = prompts_dir / md_filename
        
        with open(md_filepath, 'w', encoding='utf-8') as f:
            f.write(f"# {section_name.upper()} PROMPT\n\n")
            f.write(f"**Stock Symbol:** {stock_symbol}\n\n")
            f.write(f"**Generated:** {pd.Timestamp.now().isoformat()}\n\n")
            f.write(f"**Prompt Length:** {len(prompt_content)} characters\n\n")
            f.write("---\n\n")
            f.write(prompt_content)
        
        # Save as HTML
        html_filename = f"prompt_{stock_symbol}_{section_name}_{timestamp}.html"
        html_filepath = prompts_dir / html_filename
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{section_name.upper()} Prompt - {stock_symbol}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
            color: #333;
            line-height: 1.6;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }}
        h1 {{
            margin: 0 0 10px 0;
            font-size: 28px;
        }}
        .meta {{
            font-size: 14px;
            opacity: 0.9;
        }}
        .meta p {{
            margin: 5px 0;
        }}
        .prompt-container {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .prompt-content {{
            white-space: pre-wrap;
            word-wrap: break-word;
            font-family: 'Courier New', monospace;
            background-color: #f8f9fa;
            padding: 15px;
            border-left: 4px solid #667eea;
            border-radius: 4px;
            overflow-x: auto;
            font-size: 14px;
        }}
        .footer {{
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{section_name.upper()} PROMPT</h1>
        <div class="meta">
            <p><strong>Stock Symbol:</strong> {stock_symbol}</p>
            <p><strong>Generated:</strong> {pd.Timestamp.now().isoformat()}</p>
            <p><strong>Prompt Length:</strong> {len(prompt_content)} characters</p>
        </div>
    </div>
    
    <div class="prompt-container">
        <h2>Prompt Content</h2>
        <div class="prompt-content">{prompt_content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')}</div>
    </div>
    
    <div class="footer">
        <p>Debug prompt saved on {pd.Timestamp.now().strftime('%A, %B %d, %Y at %H:%M:%S')}</p>
        <p><em>This file was automatically generated by the Stock Analyzer debug system.</em></p>
    </div>
</body>
</html>"""
        
        with open(html_filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        logger.info(f"✓ Saved prompt files:")
        logger.info(f"  - Markdown: {md_filepath}")
        logger.info(f"  - HTML: {html_filepath}")
        
        return str(md_filepath), str(html_filepath)
    
    except Exception as e:
        logger.warning(f"Could not save prompt files: {e}")
        return None, None
